### ISSUE TITLE
DDP disconnection issue when calling Meteor.users.remove

### ISSUE THREAD

**Issue by danimbrogno** [xolvio/automated-testing-best-practices#11]
Ran into this issue when writing a feature for a user deleting their own account. 

When I call the function `Meteor.users.remove({_id:user._id});` on the server, chimp throws this error from my cucumber feature:

 `Then my account should be deleted                   # tests/features/user-delete.feature:8
      Error: Promise was fulfilled but got rejected with the following reason: Error: DDPClient: Disconnected from DDP server
        at World.<anonymous> (features/step_definitions/domain/Then my account should be deleted.js:5:10)`

I've reproduced this issue here so you can have a look. 
https://github.com/3VLINC/automated-testing-best-practices

I apologize but I haven't been able to get node-inspector working well with this setup yet so I haven't been able to do much debugging otherwise.

Any insight would be appreciated.

**Comment by SamHatoum** [comment]
Try to do a `server.call('logout')` first

**Comment by danimbrogno** [comment]
I can't log the user out before deleting their account, because my server function depends on Meteor.user() in order to get the id of the currently logged in user, verify they have permission to delete their account and then do the actual deleting. I tried invalidating the users login token on the server before logging them out, but I still experience the same issue. What about deleting a user account would cause the DDPClient to disconnect? I'm not too familiar with how DDP works. I find it strange that it works fine when running not in the development environment, but the test environment causes an error.

**Comment by SamHatoum** [comment]
It's the DDP connection implementation. It needs to be logged out before you delete the user it is logged in with, otherwise it gets into an inconsistent state.

Your other option is to create a fixture package that is debug only which does the resetting. That way you can log out, and the call to reset does not need authentication.

**Comment by danimbrogno** [comment]
Ahh! I see this problem is actually caused by the xolvio:cleaner package. I didn't grasp that at first. I was able to fix the problem by changing the database reset script in hooks.js, and telling Meteor to logout, before running the resetDatabase function. 

```
module.exports = function() {

  this.Before(function() {

    global.CRITICAL = false;

    server.execute(
    	function() {

            Meteor.call('logout');

            Package['xolvio:cleaner'].resetDatabase();

    		Accounts.removeDefaultRateLimit();

    	}
    );

  });

};
```
