### ISSUE TITLE
Feature request: Chimp mocha tests example

### ISSUE THREAD

**Issue by kristijanhusak** [xolvio/automated-testing-best-practices#15]
This best practices covers almost all types of testing, except mocha tests that are ran with `chimp --mocha` like explained here https://chimp.readme.io/docs/getting-started-mocha. Will they maybe be added? I tried to add them myself, but i always get `describe is not defined`. Am I doing something wrong?

**Comment by SamHatoum** [comment]
can you show me the file you're using?

**Comment by kristijanhusak** [comment]
I managed to run it on another machine, not sure why it didn't work on the first one, will try it at Monday. Anyway, few mocha tests with npm script to run them would be good, just to have it as an example.
