### ISSUE TITLE
Meteor App exited with code -2

### ISSUE THREAD

**Issue by zodern** [xolvio/automated-testing-best-practices#2]
When I run `npm start`, I get:

```
$ npm start

> .scripts/start.js

Meteor App exited with code -2
```

**Comment by SamHatoum** [comment]
Is this on a fresh checkout of this this repo?
Do you have Meteor installed?

**Comment by zodern** [comment]
I had copied the package.json and .scripts folder to my app. I changed the srcDir in start.js and it now works.

**Comment by SamHatoum** [comment]
awesome
