### ISSUE TITLE
Fixtures examples

### ISSUE THREAD

**Issue by shrop** [xolvio/automated-testing-best-practices#21]
Do you have recommendations on where to place fixtures and writing them?

**Comment by shrop** [comment]
Going to close. Thinking I should ask on forums.meteor.com. :)

**Comment by zvictor** [comment]
I would recommend having them as a package. This way you can use the same fixtures for testing and development modes.

You can also do more tricky things with a package, like creating a public folder inside the package where you add images related to the fixtures only, like logos and profile pictures.
