### ISSUE TITLE
npm install fails in windows & wallaby also fails

### ISSUE THREAD

**Issue by lucidprogrammer** [xolvio/automated-testing-best-practices#22]
C:\Users\projects\automated-testing-best-practices>npm install
## npm WARN deprecated react-tools@0.12.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated

> fibers@1.0.10 install C:\Users\projects\automated-testing-best-practices\node_modules\chimp\node_modules\fibers
> node build.js || nodejs build.js

\
C:\Users\projects\automated-testing-best-practices\node_modules\chimp\node_modules\fibers>node "D:\programs\node\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild --release
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\Users\projects\automated-testing-best-practices\no
de_modules\chimp\node_modules\fibers\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\programs\node\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "D:\programs\node\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\projects\automated-testing-best-practices\node_modules\chimp\node_modules\fibers
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
Build failed
'nodejs' is not recognized as an internal or external command,
operable program or batch file.

npm WARN optional dep failed, continuing fsevents@1.0.8
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm ERR! fibers@1.0.10 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.10 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "D:\programs\node\\node.exe" "D:\programs\node\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! cwd C:\Users\projects\automated-testing-best-practices
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

---

wallaby console
Configuration:wallaby.js
Unexpected token >

Any suggestions?

**Comment by SamHatoum** [comment]
which version of node are you using?

**Comment by lucidprogrammer** [comment]
I am on 10.4, ok i move up?

**Comment by SamHatoum** [comment]
yep!

**Comment by lucidprogrammer** [comment]
Using v5.2.0 of node. Following change to the package.json file for it to work in windows.

```
 "scripts": {
    "start": "node .scripts/start.js",
    "test": "node .scripts/test.js"
  }

```

But I get the following errors, and unable to find a solution.
c:\Users\projects\automated-testing-best-practices>npm start

> @ start c:\Users\projects\automated-testing-best-practices
> node .scripts/start.js

[[[[[ c:\Users\projects\automated-testing-best-practices\src ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Exited with code: 8
W20160226-06:39:01.547(0)? (STDERR)
W20160226-06:39:01.548(0)? (STDERR) c:\Users\projects\automated-testing-best-practices\node_modules\fibers\fibers.js:16
W20160226-06:39:01.548(0)? (STDERR)     throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
W20160226-06:39:01.548(0)? (STDERR)           ^
W20160226-06:39:01.549(0)? (STDERR) Error:`c:\Users\projects\automated-testing-best-practices\node_modules\fibers\bin\win32-ia32-v8-3.14\fibers.node`is missing. Try reinstalling`node-fibers`?
W20160226-06:39:01.549(0)? (STDERR)     at Object.<anonymous> (c:\Users\projects\automated-testing-best-practices\node_modules\fibers\fibers.js:16:8)
W20160226-06:39:01.549(0)? (STDERR)     at Module._compile (module.js:456:26)
W20160226-06:39:01.549(0)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160226-06:39:01.549(0)? (STDERR)     at Module.load (module.js:356:32)
W20160226-06:39:01.550(0)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160226-06:39:01.550(0)? (STDERR)     at Module.require (module.js:364:17)
W20160226-06:39:01.550(0)? (STDERR)     at require (module.js:380:17)
W20160226-06:39:01.550(0)? (STDERR)     at Object.<anonymous> (c:\Users\projects\automated-testing-best-practices\src\.meteor\local\build\programs\server\boot.js:1:75)
W20160226-06:39:01.550(0)? (STDERR)     at Module._compile (module.js:456:26)
W20160226-06:39:01.550(0)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
=> Exited with code: 8
W20160226-06:39:08.540(0)? (STDERR)
W20160226-06:39:08.540(0)? (STDERR) c:\Users\projects\automated-testing-best-practices\node_modules\fibers\fibers.js:16
W20160226-06:39:08.540(0)? (STDERR)     throw new Error('`'+ modPath+ '.node`is missing. Try reinstalling`node-fibe
W20160226-06:39:08.540(0)? (STDERR)           ^
W20160226-06:39:08.540(0)? (STDERR) Error: `c:\Users\projects\automated-testing-best-practices\node_modules\fibers\bin\win32-ia32-v8-3.14\fibers.node` is missing. Try reinstalling `node-fibers`?
W20160226-06:39:08.540(0)? (STDERR)     at Object.<anonymous> (c:\Users\projects\automated-testing-best-practices\node_modules\fibers\fibers.js:16:8)
W20160226-06:39:08.540(0)? (STDERR)     at Module._compile (module.js:456:26)
W20160226-06:39:08.540(0)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160226-06:39:08.540(0)? (STDERR)     at Module.load (module.js:356:32)
W20160226-06:39:08.540(0)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160226-06:39:08.540(0)? (STDERR)     at Module.require (module.js:364:17)
W20160226-06:39:08.540(0)? (STDERR)     at require (module.js:380:17)
W20160226-06:39:08.540(0)? (STDERR)     at Object.<anonymous> (c:\Users\projects\automated-testing-best-practices\src.meteor\local\build\programs\server\boot.js:1:75)
W20160226-06:39:08.540(0)? (STDERR)     at Module._compile (module.js:456:26)
W20160226-06:39:08.540(0)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
W20160226-06:39:15.084(0)? (STDERR)
W20160226-06:39:15.084(0)? (STDERR) c:\Users\projects\automated-testing-best-practices\node_modules\fibers\fibers.js:16
W20160226-06:39:15.084(0)? (STDERR)     throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
W20160226-06:39:15.084(0)? (STDERR)           ^
W20160226-06:39:15.084(0)? (STDERR) Error:`c:\Users\projects\automated-testing-best-practices\node_modules\fibers\bin\win32-ia32-v8-3.14\fibers.node`is missing. Try reinstalling`node-fibers`?
W20160226-06:39:15.084(0)? (STDERR)     at Object.<anonymous> (c:\Users\projects\automated-testing-best-practices\node_modules\fibers\fibers.js:16:8)
W20160226-06:39:15.084(0)? (STDERR)     at Module._compile (module.js:456:26)
W20160226-06:39:15.084(0)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160226-06:39:15.084(0)? (STDERR)     at Module.load (module.js:356:32)
W20160226-06:39:15.084(0)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160226-06:39:15.084(0)? (STDERR)     at Module.require (module.js:364:17)
W20160226-06:39:15.084(0)? (STDERR)     at require (module.js:380:17)
W20160226-06:39:15.084(0)? (STDERR)     at Object.<anonymous> (c:\Users\projects\automated-testing-best-practices\src.meteor\local\build\programs\server\boot.js:1:75)
W20160226-06:39:15.084(0)? (STDERR)     at Module._compile (module.js:456:26)
W20160226-06:39:15.084(0)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
^CTerminate batch job (Y/N)?
^C
c:\Users\projects\automated-testing-best-practices>

c:\Users\projects\automated-testing-best-practices>npm test

> @ test c:\Users\projects\automated-testing-best-practices
> node .scripts/test.js

26 02 2016 06:39:30.130:INFO [karma]: Karma v0.13.21 server started at http://localhost:9876/
26 02 2016 06:39:30.152:INFO [launcher]: Starting browser Chrome
26 02 2016 06:39:31.435:INFO [Chrome 48.0.2564 (Windows 10 0.0.0)]: Connected on socket /#tMuJqNBGDkIRJZyjAAAA with id 12286
Chrome 48.0.2564 (Windows 10 0.0.0): Executed 1 of 4 SUCCESS (0 secs / 0.003 secChrome 48.0.2564 (Windows 10 0.0.0): Executed 2 of 4 SUCCESS (0 secs / 0.003 secChrome 48.0.2564 (Windows 10 0.0.0): Executed 3 of 4 SUCCESS (0 secs / 0.014 secChrome 48.0.2564 (Windows 10 0.0.0): Executed 4 of 4 SUCCESS (0 secs / 0.025 secChrome 48.0.2564 (Windows 10 0.0.0): Executed 4 of 4 SUCCESS (0.033 secs / 0.025 secs)
Velocity exited with code 8
npm ERR! Test failed.  See above for more details.

---

Tried installing fibers, which seems ok
c:\Users\projects\automated-testing-best-practices>npm install fibers
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN install Couldn't install optional dependency: Unsupported

> fibers@1.0.10 install c:\Users\projects\automated-testing-best-practices\node_modules\fibers
> node build.js || nodejs build.js

`win32-x64-v8-4.6` exists; testing
Binary is fine; exiting
c:\Users\projects\automated-testing-best-practices
└── fibers@1.0.10

**Comment by SamHatoum** [comment]
Did you try deleting the `node_modules` folder first? The one inside the `.scripts` folder too

**Comment by lucidprogrammer** [comment]
yes. deleted the entire app and did fresh all each time.

**Comment by lucidprogrammer** [comment]
also removed npm-cache and previous npm in system folder before doing, just in case

**Comment by lucidprogrammer** [comment]
In the error log it says the following is missing c:\Users\projects\automated-testing-best-practices\node_modules\fibers\bin\win32-ia32-v8-3.14\fibers.node

However, when it does binary test it is checking win32-x64-v8-4.6 

I am on a 64 bit machine, node installed is 64 bit.

**Comment by SamHatoum** [comment]
Can you try bumping Chimp to the latest version? 0.30.0

**Comment by lucidprogrammer** [comment]
removed the node_modules and then did npm install with "chimp": "0.30.0", in "devDependencies". No luck, the same error persisting.

**Comment by lucidprogrammer** [comment]
Ok I did some more trials with no luck, but hopefully could help you identify the issue.

the error is coming from this in fibers.js

`var v8 = 'v8-'+ /[0-9]+\.[0-9]+/.exec(process.versions.v8)[0];
var modPath = path.join(__dirname, 'bin', process.platform+ '-'+ process.arch+ '-'+ v8, 'fibers');
try {
    fs.statSync(modPath+ '.node');
} catch (ex) {
    // No binary!
    throw new Error('`'+ modPath+ '.node`is missing. Try reinstalling`node-fibers`?');
}`

So this is giving the error as c:\Users\projects\automated-testing-best-practices\node_modules\fibers\bin\win32-ia32-v8-3.14\fibers.node is missing.

If I run the node in terminal, and try the following,
`> var v8 = 'v8-'+ /[0-9]+.[0-9]+/.exec(process.versions.v8)[0];
undefined

> v8
> 'v8-4.6'
> process.arch
> 'x64'`

So somewhere those are getting changed. However, if I add the following 
`modPath = path.join(__dirname, 'bin', process.platform+ '-'+ 'x64'+ '-'+ 'v8-4.6', 'fibers');`

(that is the actual fibers install coming through. npm start gives the following.

W20160226-08:08:29.498(0)? (STDERR) module.js:356
W20160226-08:08:29.498(0)? (STDERR)   Module._extensions[extension](this, filename);
W20160226-08:08:29.498(0)? (STDERR)                                ^
W20160226-08:08:29.498(0)? (STDERR) Error: %1 is not a valid Win32 application.
W20160226-08:08:29.498(0)? (STDERR)
W20160226-08:08:29.498(0)? (STDERR) c:\Users\projects\automated-testing-best-practices\node_modules\fibers\bin\win32-x64-v8-4.6\fibers.node
W20160226-08:08:29.498(0)? (STDERR)     at Module.load (module.js:356:32)
W20160226-08:08:29.498(0)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160226-08:08:29.498(0)? (STDERR)     at Module.require (module.js:364:17)
W20160226-08:08:29.498(0)? (STDERR)     at require (module.js:380:17)
W20160226-08:08:29.498(0)? (STDERR)     at Object.<anonymous> (c:\Users

Tks

**Comment by ghost** [comment]
You need to install chimp in the .scripts folder instead of the app root folder. Because otherwise Meteor tries to use the fibers package that Chimp depends on, which doesn't work. This is already fixed in https://github.com/xolvio/automated-testing-best-practices/tree/wip/migrate_1.3.

**Comment by lucidprogrammer** [comment]
That branch works. Thank you, great work.

As of now, it doesn't show any status or reports (velocity?), will watch this repository for updates.
