### ISSUE TITLE
chimp 0.31.0 breaking the tests

### ISSUE THREAD

**Issue by lgandecki** [xolvio/automated-testing-best-practices#30]
Tests are breaking when trying to use chimp 0.31.0 .

I need 0.31.0 to set up parallelization - to pass feature files as arguments to chimp, instead of specifying --path. 

```
When I deposit the check into my account
  Error: Underlying driver does not implement advanced user interactions yet.
When I transfer $20 to "James"'s bank account
  Error: Underlying driver does not implement advanced user interactions yet.
```

You can reproduce this in https://github.com/lgandecki/automated-testing-best-practices/tree/withChimp0.31.0

If we use https://github.com/xolvio/chimp/tree/multidriver instead, or 0.30.0 it passes.

**Comment by ghost** [comment]
Hi, can you try Chimp 0.31.1. Should be already fixed.

**Comment by lgandecki** [comment]
That's it! Thanks a lot, you guys are too fast!
