### ISSUE TITLE
Chimp.js + Meteor 1.3 + Codeship or CircleCI  continuous integration

### ISSUE THREAD

**Issue by Oizor** [xolvio/automated-testing-best-practices#38]
Is there already an easy way to run Chimp.js and Meteor 1.3 on a CI service like Codeship of CircleCI? The main obstacle I'm facing is how to determine Meteor has fully started before executing the chimp command.

**Comment by ghost** [comment]
See https://github.com/xolvio/automated-testing-best-practices/blob/master/circle.yml#L56 for the CircleCI config. We do the start logic in the scripts/test.js.
