### ISSUE TITLE
Are screenshots on error only a cucumber feature?

### ISSUE THREAD

**Issue by radixhound** [xolvio/automated-testing-best-practices#45]
I am trying to get screenshots on error to work but our tests are strictly mocha + webdriver tests (no cucumber) Is that the reason I can't get it to work? When it errors I have no screenshots on CI and so I tried debugging by setting them up locally like this:

``` javascript
scrnBin = path.resolve(baseDir, 'screenshots');
if (process.env.CIRCLECI) {
  chimpSwitches += ' --screenshotsPath="' + process.env.CIRCLE_ARTIFACTS + '"';
} else {
  chimpSwitches += ' --screenshotsPath="'+ scrnBin + '" --screenshotsOnError=1';
}
```

(I also tried `screensotsOnError=true`)
No screenshots to be found.

Hmm I think I answered my own issue by [looking at the source repo](https://github.com/xolvio/chimp/blob/1456f7094db261c924e93087d7a32221f6b3ccad/src/bin/chimp.js#L27-L33). If this is the case, perhaps you can [update the documentation](https://chimp.readme.io/#section--automatically-takes-screenshots-on-failures-) because it's misleading. Maybe "When using cucumber, Chimp can save them to file or include..."

**Comment by ghost** [comment]
Yeah, seems to be supported for Cucumber only currently. I think it has been forgotten when Mocha support was first introduced and I didn't implement it Jasmine either. I think opening an enhancement ticket would be the right thing to do.
