### ISSUE TITLE
npm start is broken for systems where npm & node are not located in the same directory

### ISSUE THREAD

**Issue by cwohlman** [xolvio/automated-testing-best-practices#5]
Related to (and caused by) https://github.com/xolvio/chimp/issues/149, I get this bug because I installed node via brew.

I also noticed this in the comments, which might mean that the script in this repo is using the wrong copy of node?:

> when running Meteor, we have to use the Meteor specific one. 

https://github.com/xolvio/chimp/issues/149#issuecomment-156946556

**Comment by SamHatoum** [comment]
Fixed in chimp 0.24.0
