### ISSUE TITLE
is it possible to run wallaby on meteor 1.2.1 ?

### ISSUE THREAD

**Issue by Alino** [xolvio/automated-testing-best-practices#51]
I would like to implement wallaby.js to my project but I am currently stuck on meteor 1.2 and I cannot easily upgrade to version 1.3 because that breaks the whole app due to ES6 modules. ( I am on package based architecture like telescope app )
The velocity package tests currently take too much time to load and to rerun them, it's pain to run the test because I don't want to wait like 30 seconds until they rerun.
What is your opinion please, what should I do.
- Is there an easy way to run wallaby on meteor 1.2?
- Should I rewrite the architecture (40 custom packages) to ES6 module style and use wallaby then? (this will be a huge task I think)
- any other suggestions? :)

Thank you very much for everything you do at xolvio!

**Comment by SamHatoum** [comment]
It is possible. You would need to load the [velocity/stubs](https://github.com/meteor-velocity/meteor-stubs) project into Wallaby and extend it somewhat yourself. It's not trivial and I would suggest you take the plunge and start converting your app to a modular approach to get to that.

To get there iteratively, you can introduce a thin indirection layer for all Meteor specific objects like `Collections` etc, and use a dependency injection approach to allow wallaby to load your app files independently of the Meteor specific thin indirection layer. This way you can use standard wallaby node configurations and make sure the logic of your app works.

Hope that helps, if you need further assistance [we do offer this](http://xolv.io/services/meteor-testing-support/) :)

**Comment by Alino** [comment]
thank you for your answer. I will try to dive into using es6 modules. If I will need further help with this I would contact you. :)
