### ISSUE TITLE
are you leaving meteor?

### ISSUE THREAD

**Issue by Alino** [xolvio/automated-testing-best-practices#63]
I have noticed some recent pushes into dev branch.
And I didn't see meteor in there, so I wonder if the dev branch is going to become a master branch in some point of time. Or are you going to maintain 2 versions of this repo with and without meteor?

**Comment by SamHatoum** [comment]
Meteor will be added to that branch. I'm just putting it in a box and not letting it drive the app. Rather, is y used by the app.

**Comment by Alino** [comment]
ok thank you for clarification :)
