### ISSUE TITLE
why mocha and not jasmine, in the dev branch?

### ISSUE THREAD

**Issue by Alino** [xolvio/automated-testing-best-practices#65]
I am used now to jasmine, also thanks to your previous work with sanjo:jasmine and so on. Please could you explain the reason of this switch?

**Comment by SamHatoum** [comment]
Mocha is more extensible and therefore gives users more options. For example, you can still [use jasmine assertions](https://github.com/xolvio/jasmine-expect) with it using this if you want to keep the same tests. 

Mocha also has [better reporter options](https://mochajs.org/#reporters) and [diff views](https://mochajs.org/#diffs).

It's super easy to apply what you see in Jasmine if you prefer it. There's some minor syntax differences but that's about it.

**Comment by Alino** [comment]
cool thanks, I didn't know that I can use mocha and keep my tests with jasmine assertions library. And those mocha reporters look amazing. So it seems that I am going to switch to mocha.
