### ISSUE TITLE
A place for common support files

### ISSUE THREAD

**Issue by zvictor** [xolvio/automated-testing-best-practices#7]
_First of all, thank you very much for sharing this great project with the community. Xolvio work is a splendid piece of art!_

I am moving my old project's files around to be compliant with the structure presented in this repository, but something is making me confused.

Before, I had all my **support** files located at  `tests/cucumber/features/_support/`. Where should I put them now? It seems that I should move them to `src/tests/features/step_definitions/domain/support`, right? If that's the case, how can I share support files between `domain`  and `critical`? Shouldn't we have common support files accessible at `src/tests/features/step_definitions/support`?

**Comment by SamHatoum** [comment]
Thank you for the kind words!

Everything under `domain` is also accessible from `critical`. Domain is common really. If you prefer to have a discreet common directory, you can do so by adding another `-r` / `--require` path, [like this](https://github.com/xolvio/automated-testing-best-practices/blob/master/.scripts/start.js#L37).

**Comment by zvictor** [comment]
Thank you for the clarification. It is enough like that :smile:
